#!/bin/bash

mkdir -p "$(dirname "$0")/deluge-config"
mkdir -p "$(dirname "$0")/etc-openvpn"

downloadslocation="$1"

if [ -z "$downloadslocation" ]; then
	>&2 echo 'Usage: run <downloads location>'
	exit
fi

username=torrenter

docker run \
  -d \
  --rm \
  --cap-add NET_ADMIN \
  --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  --name deluge-with-openvpn-container \
  -p 127.0.0.1:8112:8112 \
  -v "$(readlink -f "$(dirname "$0")")/deluge-config:/home/$username/.config/deluge" \
  -v "$(readlink -f "$(dirname "$0")")/etc-openvpn:/etc/openvpn" \
  -v "$(readlink -f "$downloadslocation"):/home/$username/Downloads" \
  deluge-with-openvpn $username $(id -u $(whoami)) $(id -g $(whoami))

# https://github.com/haugene/docker-transmission-openvpn/issues/960
